server:
  port: 8080
  context-path: /blog
spring:
  datasource:
    url: jdbc:mysql://45.77.113.201:3306/blog?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
  redis:
    #redis数据库索引(默认为0)
    database: 0
    #redis服务器地址
    host: 45.77.113.201
    #端口
    port: 6379
    #redis服务器连接密码(默认为空)
    password:
    timeout: 0
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
    # 连接超时时间(ms)
  kafka:
    producer:
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      bootstrap-servers: 112.74.40.100:9092
    consumer:
      bootstrap-servers: 112.74.40.100:9092
      group-id: zjm-test
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
mybatis:
  config-location: classpath:sqlmap/sqlmap-config.xml
